### PR TITLE
Add pom.xml bits to enable publishing to artifactory

### PR DESCRIPTION
**Pull request by dsyer**

### CODE REVIEW

**Comment by glyn** [comment]
@dsyer This PR now has a conflict. If it is still needed, would you be happy to resubmit it against the upcoming monorepo?

**Comment by dsyer** [comment]
I suppose so. The change is trivial so I doubt if it is hard to resolve, but I’m away from my desk now so go ahead if you need to make progress and need my input.

**Comment by glyn** [comment]
Thanks @dsyer. We've decided to leave open any PRs we cannot merge (or close because they are not needed). They will then be available for porting across to the monorepo and closing at that point.

**Comment by ericbottard** [comment]
Fixed and merged as 675748b

**Pull request closed without merging**
